version: '3.8'
services:
  net-application:
    container_name: net-application
    image: 13072347/docker-app
    restart: always
    networks:
      - mynetwork

  grafana:
    container_name: grafana-test
    image: grafana/grafana:latest
    volumes:
      - ./grafana/:/var/lib/grafana/
    networks:
      - mynetwork

  prometheus:
    container_name: prometheus-test
    image: prom/prometheus:latest
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      - mynetwork

  jenkins:
    container_name: jenkins-test
    image: jenkins/jenkins:lts
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins/jenkins_home/:/var/jenkins_home/
    networks:
      - mynetwork

  nginx:
    container_name: ingress-test
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  mynetwork:
    driver: bridge